import { email, required } from "utils/validate.util";
import InputRedux from "components/molecules/InputRedux";
import { ReduxFormField } from "components/molecules/ReduxFormFields";
import SelectRedux from "components/molecules/SelectRedux";
import DatePickerRedux from "components/molecules/DatePickerRedux";
import PhoneInputRedux from "components/molecules/PhoneInputRedux";

export { default } from "./RegisterForm";

export const fields: ReduxFormField[] = [
  {
    name: "name",
    label: "Name",
    validate: [required],
    component: InputRedux,
    cellProps: { md: 12 },
  },
  {
    name: "race",
    label: "Race",
    validate: [required],
    component: SelectRedux,
    SelectProps: {
      options: [
        { value: "Anime", label: "Anime" },
        { value: "Human", label: "Human" },
        { value: "King", label: "King" },
        { value: "Queen", label: "Queen" },
        { value: "Princess", label: "Princess" },
        { value: "Prince", label: "Prince" },
        { value: "Knight", label: "Knight" },
        { value: "Vampire", label: "Vampire" },
        { value: "Werewolf", label: "Werewolf" },
        { value: "Maid", label: "Maid" },
        { value: "Butler", label: "Butler" },
        { value: "Goddess", label: "Goddess" },
        { value: "God", label: "God" },
        { value: "Angel", label: "Angel" },
        { value: "Devil", label: "Devil" },
        { value: "Demon", label: "Demon" },
        { value: "Succubus", label: "Succubus" },
        { value: "Incubus", label: "Incubus" },
        { value: "Mermaid", label: "Mermaid" },
        { value: "Merman", label: "Merman" },
        { value: "Hunter", label: "Hunter" },
        { value: "Huntress", label: "Huntress" },
        { value: "Witch", label: "Witch" },
        { value: "Wizard", label: "Wizard" },
        { value: "Animal", label: "Animal" },
        { value: "Alpha", label: "Alpha" },
        { value: "Beta", label: "Beta" },
        { value: "Omega", label: "Omega" },
        { value: "Wolf", label: "Wolf" },
        { value: "Lion", label: "Lion" },
        { value: "Lioness", label: "Lioness" },
        { value: "Furry", label: "Furry" },
        { value: "Pirate", label: "Pirate" },
        { value: "Zombie", label: "Zombie" },
        { value: "Ghost", label: "Ghost" },
        { value: "Alien", label: "Alien" },
        { value: "Robot", label: "Robot" },
        { value: "Android", label: "Android" },
        { value: "Cyborg", label: "Cyborg" },
        { value: "Fairy", label: "Fairy" },
        { value: "Centaur", label: "Centaur" },
        { value: "Dragon", label: "Dragon" },
        { value: "Pokemon", label: "Pokemon" },
        { value: "Digimon", label: "Digimon" },
        { value: "Dragon Ball", label: "Dragon Ball" },
        { value: "Sailor Moon", label: "Sailor Moon" },
        { value: "RWBY", label: "RWBY" },
      ],
    },
    cellProps: { md: 12 },
  },
  {
    name: "gender",
    label: "Gender",
    validate: [required],
    component: SelectRedux,
    SelectProps: {
      options: [
        { value: "male", label: "Male" },
        { value: "female", label: "Female" },
      ],
    },
    cellProps: { lg: 12 },
  },

  {
    name: "email",
    label: "Email",
    validate: [required, email],
    component: InputRedux,
    cellProps: { md: 12 },
    InputProps: { type: "email" },
  },
  {
    name: "password",
    label: "Password",
    // validate: [required],
    component: InputRedux,
    cellProps: { md: 12 },
    InputProps: { showIcon: true, type: "password" },
  },
  {
    name: "dob",
    label: "Date of Birth",
    // validate: [date],
    component: DatePickerRedux,
    cellProps: { md: 12 },
    DatePickerProps: {
      onChange: () => {},
      maxDate: new Date(),
      InputFieldProps: {},
      value: { date: "", error: false },
    },
  },
  {
    name: "age",
    label: "Age",
    validate: [required],
    component: InputRedux,
    cellProps: { md: 12 },
    InputProps: { disabled: true },
  },
  {
    name: "star",
    label: "Star Sign",
    validate: [required],
    component: InputRedux,
    cellProps: { md: 12 },
    InputProps: { disabled: true },
  },
  {
    name: "zodiac",
    label: "Zodiac Animal",
    validate: [required],
    component: InputRedux,
    cellProps: { md: 12 },
    InputProps: { disabled: true },
  },
  {
    name: "planet",
    label: "Planet",
    validate: [required],
    component: InputRedux,
    cellProps: { md: 12 },
    InputProps: { disabled: true },
  },
];

export const updateFields: ReduxFormField[] = [
  // {
  //   name: "hair",
  //   label: "Hair Color",
  //   component: SelectRedux,
  //   SelectProps: {
  //     options: [
  //       { value: "red", label: "Red" },
  //       { value: "pink", label: "Pink" },
  //       { value: "purple", label: "Purple" },
  //       { value: "yellow", label: "Yellow" },
  //       { value: "orange", label: "Orange" },
  //       { value: "blue", label: "Blue" },
  //       { value: "green", label: "Green" },
  //       { value: "brown", label: "Brown" },
  //       { value: "black", label: "Black" },
  //       { value: "grey", label: "Grey" },
  //       { value: "white", label: "White" },
  //     ],
  //   },
  //   cellProps: { lg: 12 },
  // },
  // {
  //   name: "eyes",
  //   label: "Eyes Color",
  //   component: SelectRedux,
  //   SelectProps: {
  //     options: [
  //       { value: "red", label: "Red" },
  //       { value: "pink", label: "Pink" },
  //       { value: "purple", label: "Purple" },
  //       { value: "yellow", label: "Yellow" },
  //       { value: "orange", label: "Orange" },
  //       { value: "blue", label: "Blue" },
  //       { value: "green", label: "Green" },
  //       { value: "brown", label: "Brown" },
  //       { value: "black", label: "Black" },
  //       { value: "grey", label: "Grey" },
  //       { value: "white", label: "White" },
  //     ],
  //   },
  //   cellProps: { lg: 12 },
  // },
  // {
  //   name: "height",
  //   label: "Height",
  //   component: InputRedux,
  //   cellProps: { md: 12 },
  // },
  // {
  //   name: "weight",
  //   label: "Weight",
  //   component: InputRedux,
  //   cellProps: { md: 12 },
  // },
  // {
  //   name: "blood",
  //   label: "Blood Type",
  //   component: SelectRedux,
  //   SelectProps: {
  //     options: [
  //       { value: "A+", label: "A+" },
  //       { value: "A-", label: "A-" },
  //       { value: "B+", label: "B+" },
  //       { value: "B-", label: "B-" },
  //       { value: "O+", label: "O+" },
  //       { value: "O-", label: "O-" },
  //       { value: "AB+", label: "AB+" },
  //       { value: "AB-", label: "AB-" },
  //     ],
  //   },
  //   cellProps: { lg: 12 },
  // },
  {
    name: "relationship",
    label: "Relationship Status",
    component: SelectRedux,
    SelectProps: {
      options: [
        { value: "single", label: "Single" },
        { value: "partner", label: "Partner" },
      ],
    },
    cellProps: { lg: 12 },
  },
  {
    name: "phone",
    label: "Phone",
    component: PhoneInputRedux,
    cellProps: { md: 12 },
  },
  // {
  //   name: "facebook",
  //   label: "Facebook",
  //   component: InputRedux,
  //   cellProps: { md: 12 },
  // },
  // {
  //   name: "instagram",
  //   label: "Instagram",
  //   component: InputRedux,
  //   cellProps: { md: 12 },
  // },
  // {
  //   name: "twitter",
  //   label: "Twitter",
  //   component: InputRedux,
  //   cellProps: { md: 12 },
  // },
  // {
  //   name: "youtube",
  //   label: "Youtube",
  //   component: InputRedux,
  //   cellProps: { md: 12 },
  // },
  // {
  //   name: "snapchat",
  //   label: "Snapchat",
  //   component: InputRedux,
  //   cellProps: { md: 12 },
  // },
  // {
  //   name: "tiktok",
  //   label: "Tiktok",
  //   component: InputRedux,
  //   cellProps: { md: 12 },
  // },
  // {
  //   name: "discord",
  //   label: "Discord",
  //   component: InputRedux,
  //   cellProps: { md: 12 },
  // },
  // {
  //   name: "paypal",
  //   label: "Paypal",
  //   component: InputRedux,
  //   cellProps: { md: 12 },
  // },
];
